# Generated by Django 5.1.1 on 2024-10-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=250)),
                ("value", models.CharField(blank=True, default="", max_length=250)),
            ],
        ),
    ]
